language: php

php:
  - '7.3'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

git:
  submodules: false

before_script:
  - make install check

script:
  - make test
